# Generated by Django 3.2.15 on 2022-09-02 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='describe your request here'),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='start_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 14, 21, 3, 864124)),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
