# Generated by Django 3.2.15 on 2022-09-03 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220903_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='start_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 12, 46, 5, 715501)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
