# Generated by Django 3.2.15 on 2022-09-03 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220903_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='start_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 13, 19, 53, 641462)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
