# Generated by Django 3.2.15 on 2022-09-04 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220904_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='res_status',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 22, 59, 24, 24646)),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
